// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDPtbGgR8BTgPz6DWNEk5S1QbY3ePi_uo',
    appId: '1:367418595590:web:614438c15be82f51f32687',
    messagingSenderId: '367418595590',
    projectId: 'collegehub-5bde3',
    authDomain: 'collegehub-5bde3.firebaseapp.com',
    storageBucket: 'collegehub-5bde3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOJYVxBTToRtHK5s4hj72SY2XPWo4g_t4',
    appId: '1:367418595590:android:5b17876bc9683710f32687',
    messagingSenderId: '367418595590',
    projectId: 'collegehub-5bde3',
    storageBucket: 'collegehub-5bde3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1gCZxDdjYrgV3sxMhvWnJGMT2HxOwatE',
    appId: '1:367418595590:ios:748a80130b797c0bf32687',
    messagingSenderId: '367418595590',
    projectId: 'collegehub-5bde3',
    storageBucket: 'collegehub-5bde3.appspot.com',
    iosBundleId: 'com.aljamia.csproject',
  );
}
